### PR TITLE
Modification of the event section

### PR DESCRIPTION
**Pull request by marcgeeklaberge**
- New Past Tab
- New Future Tab

### CODE REVIEW

**Comment by maximevaillancourt** [comment]
Nice. Maybe we could have two tabs only : "Past" and "Future" events. What do you think?

**Comment by Sytten** [comment]
As we dont have a lot of events maybe, but not convinced.

**Comment by maximevaillancourt** [comment]
Since we don't have many events for now, maybe we could just display all the events and grey out the ones that are over. Or just strikethrough the text of the past events.

**Comment by Sytten** [comment]
Nah I like to idea to see only whats going on right now. Lets try tabs: À venir, Passés, Tous
Maybe if if have more events in the future with might add a sub-bar.

**Comment by maximevaillancourt** [comment]
If you mean having a sub-bar with the categories (security, competition, etc.) when we'll have more events, then I'm fine with that. For now, I agree that we only need "Past", "Future" and "All".

**Comment by Sytten** [comment]
yes exactly. Can you change the tags? And maybe make them a bit more explicit: pass isnt very good. I say we only use the tag inactive and use the *:not(inactive) for the Future tab.

**Comment by maximevaillancourt** [comment]
How about "Past Events" and "Events to come" (Événements passés, Événements à venir) for the tab labels?

**Comment by maximevaillancourt** [comment]
Or were you talking about the code tags? like the class names? Something like ".event-to-come" and ".past-event"?

**Comment by Sytten** [comment]
Yes the code event. We dont really need two class name. For the name displayed I find the Evenement unecessary

**Comment by maximevaillancourt** [comment]
So the tab labels become "To come" and "Past" ("À venir" and "Passé")?
I agree with having only one code tag, but I would only have "active" (instead of only "inactive").
To me, having "active" and "not(active)" is clearer than "inactive" and "not(inactive)".
I don't like double negations.

**Comment by Sytten** [comment]
Agree with that. I think Passé would take an s here. Do you want to do a PL on top of this one?

**Comment by maximevaillancourt** [comment]
If by "PL" you mean "PR", then yes. I agree with the "s" in "Passés", since there are multiple past eventS.

**Comment by maximevaillancourt** [comment]
Do you prefer that we update this PR directly, or that I create a new PR to overwrite the changes in the present one?

**Comment by Sytten** [comment]
PL or PR same thing :p 
From what I know you cant edit another person PR. We should close this one and start from scratch since it contains many unless commits.

**Comment by maximevaillancourt** [comment]
Agreed. It'll save a lot of headaches in the long run.

**Comment by maximevaillancourt** [comment]
What's the preferred order for the event tabs?
1. To come
2. Past
3. All

?

**Pull request closed without merging**
