### PR TITLE
fixed quotes carousel autoplay

### PR DESCRIPTION
**Pull request by maximevaillancourt**
Fixes issue #10.
- carousel now rotates automatically (I set it to rotate every 5000ms [5 seconds])

There was no autorotate time set, so it just didn't rotate. Also, the variable should be "autoPlay" (with a capital P) instead of "autoplay" (see [this](https://stackoverflow.com/questions/22678720/owl-carousel-wont-autoplay)).

### CODE REVIEW

**Comment by DrPandemic** [comment]
:+1: seems to work. I'm not sure to understand your fix. Did you simply changed the library without changing any of our code?

**Comment by maximevaillancourt** [comment]
Nope. I "deminified" (beautified) the .js file, replaced every occurence of "autoplay" with "autoPlay", set "autoPlay" in the options to be "5000" milliseconds and minified the file again. Prior to the fix, "autoPlay" was set to "-1", which (I guess?) disables automatic rotation of the carousel.

**Comment by DrPandemic** [comment]
Ok I guess it works. But I find this weird that we need to do this. Is the library itself was broken?

**Comment by maximevaillancourt** [comment]
The library itself wasn't broken: the carousel's automatic rotation was simply disabled. I enabled it by giving the autoPlay variable an arbitrary value of 5000ms.

**Comment by DrPandemic** [comment]
This is a weird fix for the problem. I find this awkward to modify the library itself. But honestly, that's not really important. So :+1:

**Comment by maximevaillancourt** [comment]
It's not the implementation itself: it's a variable in the Options section of the file. Here is part of the Options section of the file (I only kept the important bits). See "autoPlay" (5e3 = 5 x 10³ = 5000).

2015-12-29-154555_339x234_scrot

Here is the beautified/deminified file: 

> [owl.carousel.js.txt](https://github.com/JDIS/static-website/files/74352/owl.carousel.js.txt)

The options are at the very bottom of the file.

**Comment by DrPandemic** [comment]
Wow this is weird. I wonder if we can change those settings from inside our application

**Comment by maximevaillancourt** [comment]
Maybe we could create a separate .js file and put the options there instead.

**Pull request merged**
