### PR TITLE
Updated events section

### PR DESCRIPTION
**Pull request by maximevaillancourt**
- marked past events as so
- marked future events as so
- removed event categories, replaced with "Past", "Future" and "All"
- default tab is now "Future" events

### CODE REVIEW

**Comment by maximevaillancourt** [comment]
I also added the C++ workshop event (fixes issue #25).

**Comment by DrPandemic** [comment]
Really nice. 

I'm really unsure on which tab we should start. The target of this site are sponsors and not students, so maybe showing more events could be better than showing less. What do you think?

**Comment by maximevaillancourt** [comment]
Good point. I'll admit I hadn't thought of that point of view. @Sytten previously said he preferred displaying the future events by default, though I don't know if he thought about it either. As you say, we could show all events (to impress sponsors: "look at everything we did / will do!"), then, if they want, they have the choice to see what's to come. What do you think Émile?

**Comment by marcgeeklaberge** [comment]
Perhaps we could put the tab "All" by default (First Tab).

**Comment by Sytten** [comment]
Hum well, I didnt think about that, but as you say it thats a solid point to put all the Alll tab first...
Lets do that!

**Comment by maximevaillancourt** [comment]
This PR is now closed because of branch conflicts. See #29 instead, which uses a new, clean branch.

(branch `events-fix` can thus be deleted, since `events-fix-v2` is the correct branch, used in #29)

**Pull request closed without merging**
