### PR TITLE
Added Flickr icon + link to Flickr profile

### PR DESCRIPTION
**Pull request by maximevaillancourt**
Added Flickr icon next to Facebook icon.

### CODE REVIEW

**Comment by DrPandemic** [comment]
Working well, but I think we should add a `target="_blank"` on those links to not loose the current page. That's not a strong opinion.

**Comment by marcgeeklaberge** [comment]
I agree.

**Comment by maximevaillancourt** [comment]
Done. All external links now have the `target="_blank"` attribute.

**Comment by marcgeeklaberge** [comment]
It's better like that.

**Comment by Sytten** [comment]
Perfect merging now

**Pull request merged**
