### PR TITLE
Replace event logos with hi-res ones

### PR DESCRIPTION
**Pull request by maximevaillancourt**
Logos replaced:
- CUSEC
- NorthSec

### CODE REVIEW

**Comment by maximevaillancourt** [comment]
Pinging @DrPandemic!

**Comment by DrPandemic** [comment]
The logos are really nice, but I think we should add a `height` on every square

**Comment by maximevaillancourt** [comment]
I simply updated the other logos to be square as well. Let me know what you think.

**Comment by DrPandemic** [comment]
I was thinking more about a css class. It would be easier for later use. Now if we put weirdly sized images it breaks everything

image

This is not 100% tested but it could be working

``` css
.image-wrapper {
    width: 211px;
    height: 211px;
    background-color: #f5f5f5;
}
.image-wrapper .image {
    width: 211px;
    height: 211px;
    background-size: 211px;
}
```

``` html
<div class="image-wrapper">
  <div class="image" style="background: url(https://upload.wikimedia.org/wikipedia/commons/1/1e/Large_Siamese_cat_tosses_a_mouse.jpg) no-repeat center center;"></div>
...
</div>
```

image

I'm not the biggest fan of using the background attribute to center the image, but it's kinda clean and it work well (I think). What do you think about this?

**Comment by maximevaillancourt** [comment]
Looks good! I'll admit I don't like the background attribute either, but it makes sense. Let's add the CSS part. Perhaps we could merge this PR (just to update the logos) now? Then you could add the CSS class and the updated HTML in a new PR (since you already have the code)? That way we have the new logos and we prevent weird image sizes from breaking everything.

**Comment by DrPandemic** [comment]
That sound good. :+1:

**Pull request merged**
