### PR TITLE
Hero redesign

### PR DESCRIPTION
**Pull request by maximevaillancourt**
**UPDATED: https://github.com/JDIS/static-website/pull/35#issuecomment-177312257**

---

Fixes issue #23.
- New header image
- Decreased the header height, so that we can see the content below (the user now knows he has to scroll down to see more)

sans titre

### CODE REVIEW

**Comment by DrPandemic** [comment]
Hmmmmm, I don't know if I like it. To be honest I really liked the solid green for the banner. 

Also, the height seems a little bit arbitrary. We reduce it the see the navigation. That's great, but do we need to see the start of the "Qui sommes-nous?"? I would prefer to only see the image and the header (the buttons) at the bottom. So those 2 together would represent 100% of the height.

That being said, I have no real strong opinion on the subject.

**Comment by marcgeeklaberge** [comment]
I think it's better to put the banner in full screen or not to put it at all.

**Comment by Sytten** [comment]
Not sure about the banner either, maybe something more retro (lets show some pixels) with solid green/red would be better.
I also like the full size, so I would suggest to just show the bar at the bottom.

**Comment by maximevaillancourt** [comment]
Mind if we switch our CSS to Sass/SCSS? Sass allows calculations in the attributes, so we could write something like

```
#home.full-screen-dem {
...
    height: calc(100% - $nav-bar-height);
...
}
```

This would allow to show the navigation bar, whatever the resolution.

[Here's a primer on Sass](http://sass-lang.com/guide).

**Comment by DrPandemic** [comment]
To be honest I would grunt/gulp all the project, but it would make it harder for new comer. I would love to see some sass here, but I"m not sure we should (I never thought I would ever say this). 

But `calc` is not sass it's normal css. So you simply hardcode the value and comment (again that's painful to say).

``` css
#home.full-screen-dem {
...
/* All page minus the bar (80px) */
    height: calc(100% - 80px);
...
}
```

**Comment by maximevaillancourt** [comment]
As requested, we're back to the original header. However, I did resize it vertically so we can see the navbar. Here's how it now looks.

sans titre

**Comment by DrPandemic** [comment]
:+1:

**Comment by Sytten** [comment]
Pas mal unanime, je merge!

**Pull request merged**
